//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace juba_hospital
{
    public partial class doctor_profile
    {
        protected global::System.Web.UI.WebControls.Label lblDisplayName;
        protected global::System.Web.UI.WebControls.Label lblUserRole;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Label lblUserId;
        protected global::System.Web.UI.WebControls.Label lblAccountType;
        protected global::System.Web.UI.WebControls.Label lblCurrentUsername;
        protected global::System.Web.UI.WebControls.TextBox txtNewUsername;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNewUsername;
        protected global::System.Web.UI.WebControls.Button btnUpdateUsername;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvConfirmPassword;
        protected global::System.Web.UI.WebControls.CompareValidator cvConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnUpdatePassword;
    }
}

