//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juba_hospital
{
    public partial class print_lab_revenue
    {
        protected global::System.Web.UI.WebControls.Literal litDateRange;
        protected global::System.Web.UI.WebControls.Literal litGeneratedDate;
        protected global::System.Web.UI.WebControls.Literal litGeneratedBy;
        protected global::System.Web.UI.WebControls.Literal litTotalRevenue;
        protected global::System.Web.UI.WebControls.Literal litTotalPaid;
        protected global::System.Web.UI.WebControls.Literal litTotalUnpaid;
        protected global::System.Web.UI.WebControls.Literal litTotalCharges;
        protected global::System.Web.UI.WebControls.Repeater rptLabCharges;
        protected global::System.Web.UI.WebControls.Literal litFooterTotal;
    }
}
