//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juba_hospital
{
    public partial class patient_lab_history
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// ErrorLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ErrorLiteral;

        /// <summary>
        /// ContentPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ContentPanel;

        /// <summary>
        /// PrintHeaderLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PrintHeaderLiteral;

        /// <summary>
        /// PatientNameLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PatientNameLiteral;

        /// <summary>
        /// PatientIdLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PatientIdLiteral;

        /// <summary>
        /// PatientSexLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PatientSexLiteral;

        /// <summary>
        /// PatientDOBLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PatientDOBLiteral;

        /// <summary>
        /// PatientPhoneLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PatientPhoneLiteral;

        /// <summary>
        /// PatientLocationLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PatientLocationLiteral;

        /// <summary>
        /// TotalOrdersLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal TotalOrdersLiteral;

        /// <summary>
        /// CompletedOrdersLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal CompletedOrdersLiteral;

        /// <summary>
        /// PendingOrdersLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PendingOrdersLiteral;

        /// <summary>
        /// LabHistoryLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal LabHistoryLiteral;
    }
}
