//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace juba_hospital
{


    public partial class patient_invoice_print
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// InvoiceErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel InvoiceErrorPanel;

        /// <summary>
        /// InvoiceErrorLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal InvoiceErrorLiteral;

        /// <summary>
        /// InvoicePanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel InvoicePanel;

        /// <summary>
        /// PrintHeaderLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal PrintHeaderLiteral;

        /// <summary>
        /// InvoiceGeneratedLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal InvoiceGeneratedLiteral;

        /// <summary>
        /// InvoicePatientLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal InvoicePatientLiteral;

        /// <summary>
        /// InvoicePatientIdLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal InvoicePatientIdLiteral;

        /// <summary>
        /// InvoicePhoneLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal InvoicePhoneLiteral;

        /// <summary>
        /// InvoiceLocationLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal InvoiceLocationLiteral;

        /// <summary>
        /// InvoiceDateRegisteredLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal InvoiceDateRegisteredLiteral;

        /// <summary>
        /// InvoiceVisitCountLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal InvoiceVisitCountLiteral;

        /// <summary>
        /// NoChargesPlaceholder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder NoChargesPlaceholder;

        /// <summary>
        /// ChargesTablePanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ChargesTablePanel;

        /// <summary>
        /// ChargesRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater ChargesRepeater;

        /// <summary>
        /// SummaryPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel SummaryPanel;

        /// <summary>
        /// SummaryRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater SummaryRepeater;

        /// <summary>
        /// GrandTotalLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal GrandTotalLiteral;

        /// <summary>
        /// BackButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BackButton;

        /// <summary>
        /// PrintButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button PrintButton;
    }
}

