//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace juba_hospital
{
    public partial class print_pharmacy_revenue_report
    {
        protected global::System.Web.UI.WebControls.Literal PrintHeaderLiteral;
        protected global::System.Web.UI.WebControls.Literal litDateRange;
        protected global::System.Web.UI.WebControls.Literal litFilter;
        protected global::System.Web.UI.WebControls.Literal litGeneratedDate;
        protected global::System.Web.UI.WebControls.Literal litGeneratedBy;
        protected global::System.Web.UI.WebControls.Literal litTotalRevenue;
        protected global::System.Web.UI.WebControls.Literal litTotalSales;
        protected global::System.Web.UI.WebControls.Literal litAvgSale;
        protected global::System.Web.UI.WebControls.Literal litTotalItems;
        protected global::System.Web.UI.WebControls.Repeater rptPharmacySales;
        protected global::System.Web.UI.WebControls.Literal litFooterTotal;
        protected global::System.Web.UI.WebControls.Panel pnlDailyBreakdown;
        protected global::System.Web.UI.WebControls.Repeater rptDailyBreakdown;
        protected global::System.Web.UI.WebControls.Literal litFooterHospital;
        protected global::System.Web.UI.WebControls.Literal litFooterHospitalCopyright;
    }
}
