//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juba_hospital
{
    public partial class visit_summary_print
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
