//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juba_hospital
{
    public partial class xray_revenue_report
    {
    }
}
